nelmio_api_doc:
    documentation:
        info:
            title: Wshop API
            description: This is an awesome api!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
